### ISSUE TITLE
Do you need unstable features?

### ISSUE THREAD

**Issue by tailhook** [twittner/cbor-codec#1]
Hi,

I'm evaluating use `cbor-codec` instead of `cbor` crate for my project. In particular because the latter supports only String keys in mappings. And it seems your API is a little bit nicer.

But, I want to use stable rust. So what do you think about removing unstable features? It seems there are not much to do. Do you want me to provide pull request?

**Comment by twittner** [comment]
Thanks for giving this library a try. Removing unstable features is a very good idea. I have pushed a version wich only relies on stable features to https://github.com/twittner/cbor-codec/compare/stable-features-only. Do you think this would work?

**Comment by tailhook** [comment]
Works for me. But a version on crates.io would be nice too.

**Comment by twittner** [comment]
I'll make a new release shortly.

**Comment by twittner** [comment]
Released as version [`0.1.1`](https://crates.io/crates/cbor-codec/0.1.1) to crates.io

**Comment by tailhook** [comment]
Thanks!
