### ISSUE TITLE
Config should implement std::default::Default trait

### ISSUE THREAD

**Issue by tailhook** [twittner/cbor-codec#2]
I think standard trait is better than own default function

**Comment by twittner** [comment]
I am not a fan of `std::default::Default`. The implementations of this trait are more or less arbitrary with no rules attached. What constitutes a "useful default value" is very much dependent on context. Do you have any specific use case in mind where you are limited by the current implementation?

**Comment by tailhook** [comment]
> Do you have any specific use case in mind where you are limited by the current implementation?

Well, no. I've just tried `Default::default()` first, before I've found `Config::default()`. So use your judgement.

**Comment by twittner** [comment]
I leave it like it is for now. In case there are new arguments this issue should be reopened of course.
